// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2DE1eigL7N7VXXAd7MUpC0toT6RAQvs',
    appId: '1:192449962480:android:ca9b7d6c90b561c2e43d35',
    messagingSenderId: '192449962480',
    projectId: 'l7mobile-apps',
    storageBucket: 'l7mobile-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFBswXwr2WhDZUXXc5CEZmeH_lsMoTPo',
    appId: '1:192449962480:ios:30f552a1a94f8e89e43d35',
    messagingSenderId: '192449962480',
    projectId: 'l7mobile-apps',
    storageBucket: 'l7mobile-apps.firebasestorage.app',
    androidClientId: '192449962480-4uk8i2kg6kccar4c9h3s08h6faicita0.apps.googleusercontent.com',
    iosClientId: '192449962480-7mv54objcdclj580l4gcqs5g7safpq5u.apps.googleusercontent.com',
    iosBundleId: 'com.l7mobile.aimate',
  );
}
